EDITOR_TITLES = {"properties": "CogniVal properties",
                 "main": "General Configuration",
                 "cognitive": "Cognitive Source Configuration",
                 "embedding_exp": "Embedding Experiment Configuration",
                 "embedding_conf": "Embedding Parameter Configuration"}

EDITOR_DESCRIPTIONS = { "properties": {"cognival_path": "Path for storing user data (configurations, embeddings, cognitive sources and results)."},
                        "main": {"PATH": "Main working directory. Defaults to $HOME/.cognival",
                                "cpu_count": "Number of CPU cores used for execution, defaults to (1 - number of available logical CPU cores)",
                                "folds": "Number of folds evaluated in n-Fold cross-validation (CV)",
                                "outputDir": "Output directory as subdirectory of 'results' (automatically prefixed if missing)",
                                "seed": "Random seed for train-test sampling",
                                "version": "Configuration version. Normally set to 1 when creating a new configuration file"
                                },
                       "cognitive": {"dataset": "Name of the cognitive data set. See resources/cognitive_sources.json for a list of all available source",
                                     "modality": "Cognitive source modality (eeg, eye-tracking or fmri)",
                                     "features": "Comma-separated list of features to be evaluated. Must be set to ALL_DIM for all sources with only one feature, represented by all dimensions.",
                                     "type": "'single_output' for most multi-feature resources (typically eye-tracking) and 'multivariate_output' for most single-feature resources (typicall eeg, fmri)"
                                    },
                       "embedding_exp": {"activations": "Activation function(s) used in the neural regression model. Comma-separated list for multiple values.",
                                         "batch_size": "Batch size used during training. Comma-separated list for multiple values.",
                                         "cv_split": "Number of cross-validation (CV) splits",
                                         "epochs": "Number of training epochs. Comma-separated list for multiple values.",
                                         "layers": "List of lists of layer specifications. Each row corresponds to possible layer sizes for a layer (comma-separated). Layers are separated by newlines.",
                                         "validation_split": "Ratio training data used as validation data during training"
                                        },
                        "embedding_conf":{"chunk_number": "Number of embedding chunks. Ignored if chunked == 0.",
                                         "chunked": "Whether the embedding is chunked (1) or not (0).",
                                         "chunked_file": "Prefix/root of chunk files. Ignored if chunked == 0.",
                                         "ending": "File suffix of chunk files. Ignored if chunked == 0.",
                                         "path": "Path of embedding (chunks)",
                                         "truncate_first_line": "Whether to remove the first line upon loading"
                                         }
                        }

EXAMPLE_COMMANDS = {'aggregate':[{'example':'configuration=demo [version=0] [modalities=[eye-tracking, eeg, fmri]]',
                                 'description':'Aggregate all modalities of the most recent experimental run of the configuration demo'},
                                 {'example':'configuration=demo version=1',
                                 'description':'Likewise, but for version 1 of the configuration.'},
                                 {'example':'configuration=demo modality=[eye-tracking]',
                                  'description':'Likewise, but for modality eye-tracking only.'}],
                    'config':{'properties':[{'example':'',
                                            'description':''}],
                              'open':[{'example':'',
                                       'description':''}],
                              'show':[{'example':'',
                                       'description':''}],
                              'experiment':[{'example':'',
                                             'description':''}],
                              'delete':[{'example':'',
                                         'description':''}],},
                    'install':{'cognitive-sources':[{'example':'',
                                                     'description':''}],
                              'embeddings':[{'example':'',
                                             'description':''}],
                              'random-embeddings':[{'example':'',
                                                    'description':''}]},
                    'report':[{'example':'',
                               'description':''}],
                    'run':[{'example':'',
                            'description':''}],
                    'significance':[{'example':'',
                                 'description':''}]
                     }